# Generated by Django 3.2 on 2021-04-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(max_length=264)),
                ('person2', models.CharField(max_length=264)),
                ('amount', models.FloatField(default=0.0)),
                ('reason', models.CharField(max_length=264)),
            ],
        ),
    ]
