# Generated by Django 3.2 on 2021-04-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_pairs',
            name='reason',
        ),
    ]
