# Generated by Django 3.1.6 on 2021-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210423_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_pairs',
            name='person1',
        ),
        migrations.AlterField(
            model_name='transaction_pairs',
            name='amount',
            field=models.FloatField(),
        ),
    ]
