# Generated by Django 3.2 on 2021-04-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_transaction_pairs_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_pairs',
            name='person1',
        ),
    ]
