# Generated by Django 3.2 on 2021-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_transaction_pairs_person1'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_pairs',
            name='person1',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AlterField(
            model_name='transaction_pairs',
            name='person2',
            field=models.CharField(default='', max_length=264),
        ),
    ]
