# Generated by Django 3.1.6 on 2021-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210423_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_pairs',
            name='person1',
            field=models.CharField(default='', max_length=264),
        ),
    ]
