# Generated by Django 3.2 on 2021-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210423_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_pairs',
            name='person1',
            field=models.CharField(default='Hello', max_length=264),
        ),
    ]
