# Generated by Django 3.1.6 on 2021-04-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_transaction_pairs_person1'),
        ('webapp', '0005_alter_transaction_pairs_person1'),
    ]

    operations = [
    ]
