# Generated by Django 3.1.6 on 2021-04-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_merge_20210427_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_pairs',
            name='reason',
            field=models.CharField(default=0, max_length=264),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction_pairs',
            name='person1',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='transaction_pairs',
            name='person2',
            field=models.CharField(max_length=264),
        ),
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=264)),
                ('amount', models.FloatField()),
                ('Transaction_Pairs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.transaction_pairs')),
            ],
        ),
    ]
