# Generated by Django 3.1.6 on 2021-04-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210427_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_history',
            name='Transaction_Pairs',
        ),
    ]
