# Generated by Django 3.1.6 on 2021-04-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_transaction_history_transaction_pairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_pairs',
            name='reason',
        ),
    ]
