# Generated by Django 3.1.6 on 2021-04-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_transaction_pairs_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_pairs',
            old_name='amount',
            new_name='famount',
        ),
    ]
