# Generated by Django 3.1.6 on 2021-04-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210427_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_pairs',
            name='famount',
            field=models.FloatField(null=True),
        ),
    ]
