# Generated by Django 3.1.6 on 2021-04-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210427_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_pairs',
            old_name='famount',
            new_name='amount',
        ),
    ]
