# Generated by Django 3.1.6 on 2021-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210427_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_history',
            name='amount',
        ),
        migrations.AlterField(
            model_name='transaction_pairs',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
