# Generated by Django 3.1.6 on 2021-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_transaction_history_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='person1',
            field=models.CharField(default=' ', max_length=264),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='person2',
            field=models.CharField(default=' ', max_length=264),
        ),
    ]
