# Generated by Django 3.2 on 2021-05-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20210427_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
